rvm:
  - 2.5.0
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database pgapp_test;' -U postgres
script: bundle exec rspec
deploy:
  provider: heroku
  api_key: 8f0be20f-8ab6-4717-bf13-5f76b0a68cbf
  app: blooming-meadow-10813
